# Generated by Django 2.2.6 on 2019-10-16 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodshow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooddata',
            name='image_of_food',
            field=models.ImageField(blank=True, default='general.svg', null=True, upload_to='media/food_icons/'),
        ),
    ]
