# Generated by Django 2.2.6 on 2019-11-10 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodshow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='send_daily_emails',
            field=models.BooleanField(default=True),
        ),
    ]
