# Generated by Django 2.2.6 on 2019-10-16 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodshow', '0002_auto_20191016_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fridge',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
